import * as THREE from './vendor/three.module.min.js';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const preview = $('#preview');

const planets = [
  {name:'Verdara', biome:'Lush · Gentle', color:'#68b976', sky:0x9bd5ca, ground:0x4c985c, accent:0xd8ef66, fog:0xb8ddd0},
  {name:'Emberune', biome:'Volcanic · Fierce', color:'#e56d43', sky:0x7f4d4a, ground:0x6d3923, accent:0xffa240, fog:0x85504a},
  {name:'Lumora', biome:'Biolume · Strange', color:'#5b70cf', sky:0x263a70, ground:0x31486f, accent:0x6ff4d0, fog:0x324b73},
  {name:'Aridia', biome:'Desert · Sparse', color:'#dcad5e', sky:0xe3b776, ground:0xb98542, accent:0xd5e968, fog:0xd6aa6b}
];
const traits = {
  diet:[['Herbivore','🌿',0],['Omnivore','🍎',12],['Carnivore','🦷',18]],
  body:[['Cephalized','●',0],['Fusiform','⬭',10],['Osteoderms','⬢',22]],
  mouth:[['Grinding','◡',0],['Keratin Beak','◇',8],['Carnassial','⋀',18]],
  legs:[['Plantigrade','∩',0],['Digitigrade','⟋',14],['Saltatorial','⌁',18]]
};
const colors=['#d8ef66','#ff8b62','#75ded1','#a993e9','#f2d7a0','#e95d72'];
const biology={
  body:['Cephalization concentrates sensory structures at the anterior end.','A fusiform profile reduces drag and supports efficient forward locomotion.','Osteoderms are dermal bone plates that trade flexibility and speed for protection.'],
  mouth:['Broad grinding surfaces process fibrous plant tissue.','A keratinized beak shears food without mineralized teeth.','Carnassial-like edges concentrate force for slicing animal tissue.'],
  legs:['Plantigrade feet contact the ground from heel to toe for stability.','Digitigrade posture elevates the heel and lengthens effective stride.','Saltatorial hindlimbs store and release elastic energy for jumping.']
};
const state={planet:0,diet:0,body:0,mouth:0,legs:0,color:0,budget:100,screen:'planet',bones:0,boneGoal:5,health:100,hunger:100,player:{x:0,z:0},entities:[],target:null,paused:false,tier:0,name:'Pip',spine:1,width:1,arms:0,legPairs:1,faceX:0,faceY:0};

function initUI(){
  $('#planet-list').innerHTML=planets.map((p,i)=>`<button class="planet-option ${i===0?'selected':''}" data-i="${i}"><i class="planet-orb" style="background:${p.color}"></i><span><strong>${p.name.toUpperCase()}</strong><small>${p.biome}</small></span><b>0${i+1}</b></button>`).join('');
  $$('.planet-option').forEach(b=>b.onclick=()=>{state.planet=+b.dataset.i;$$('.planet-option').forEach(x=>x.classList.toggle('selected',x===b));$('#selected-name').textContent=planets[state.planet].name.toUpperCase();buildWorld(false)});
  for(const type of ['diet','body','mouth','legs']) $(`#${type}-options`).innerHTML=traits[type].map((t,i)=>`<button class="trait-btn ${i===0?'selected':''}" data-type="${type}" data-i="${i}"><span>${t[1]}</span>${t[0]}<small>${t[2]?` · ${t[2]}`:' · FREE'}</small></button>`).join('');
  $('#color-options').innerHTML=colors.map((c,i)=>`<button class="swatch ${i===0?'selected':''}" data-i="${i}" style="background:${c}" aria-label="Color ${i+1}"></button>`).join('');
  $$('.trait-btn').forEach(b=>b.onclick=()=>selectTrait(b.dataset.type,+b.dataset.i));
  $$('.swatch').forEach(b=>b.onclick=()=>{state.color=+b.dataset.i;$$('.swatch').forEach(x=>x.classList.toggle('selected',x===b));drawPreview();refreshPlayer()});
  $('#spine-slider').oninput=e=>{state.spine=+e.target.value/100;drawPreview();refreshPlayer()};$('#width-slider').oninput=e=>{state.width=+e.target.value/100;drawPreview();refreshPlayer()};
  $$('[data-counter]').forEach(b=>b.onclick=()=>{const key=b.dataset.counter,max=key==='arms'?2:3,min=key==='arms'?0:1;state[key]=THREE.MathUtils.clamp(state[key]+ +b.dataset.delta,min,max);$('#arms-count').textContent=state.arms;$('#leg-pairs-count').textContent=state.legPairs;drawPreview();refreshPlayer()});
  $('#choose-planet').onclick=()=>showScreen('creator'); $('#back-planets').onclick=()=>showScreen('planet'); $('#begin-game').onclick=startGame;
  $('#pause-btn').onclick=()=>pause(true); $('#resume-btn').onclick=()=>pause(false); $('#restart-btn').onclick=()=>location.reload(); $('#evolve-btn').onclick=openEvolution;
  updateCreator();drawPreview();
}
function selectTrait(type,i){const old=traits[type][state[type]][2],cost=traits[type][i][2];if(state.budget+old-cost<0)return;state.budget+=old-cost;state[type]=i;updateCreator();drawPreview();refreshPlayer()}
function updateCreator(){$('#budget-value').textContent=state.budget;$$('.trait-btn').forEach(b=>{const type=b.dataset.type,i=+b.dataset.i,current=state[type];b.classList.toggle('selected',i===current);b.classList.toggle('disabled',traits[type][i][2]>state.budget+traits[type][current][2]);if(biology[type])b.title=biology[type][i]});const stats=getStats();$('#stats').innerHTML=Object.entries(stats).map(([k,v])=>`<div class="stat"><span>${k.toUpperCase()}</span><div><i style="width:${v*10}%"></i></div><b>${v}</b></div>`).join('');$('#anatomy-note').textContent=`${biology.body[state.body]} ${biology.mouth[state.mouth]} ${biology.legs[state.legs]}`}
function getStats(){return{speed:4+state.legs*2,social:5+(state.mouth===0?2:0)+(state.adaptation===2?3:0),attack:2+state.mouth*2+state.body,health:5+state.body*2}}
function showScreen(name){state.screen=name;$$('.screen').forEach(s=>s.classList.remove('active'));$(`#${name}-screen`).classList.add('active')}
let previewRenderer,previewScene,previewCamera,previewCreature,previewYaw=.35,previewPitch=.08,previewZoom=6.1,previewDrag=false,previewMode='rotate',previewLast={x:0,y:0};const previewRay=new THREE.Raycaster(),previewPointer=new THREE.Vector2();
function initPreview3D(){previewRenderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});previewRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));previewRenderer.shadowMap.enabled=true;previewRenderer.outputColorSpace=THREE.SRGBColorSpace;previewRenderer.toneMapping=THREE.ACESFilmicToneMapping;previewRenderer.toneMappingExposure=1.15;preview.appendChild(previewRenderer.domElement);previewScene=new THREE.Scene();previewCamera=new THREE.PerspectiveCamera(34,1,.1,30);previewScene.add(new THREE.HemisphereLight(0xfff7df,0x24443c,3));const key=new THREE.DirectionalLight(0xffefc9,4);key.position.set(-4,7,-4);key.castShadow=true;previewScene.add(key);const rim=new THREE.DirectionalLight(0x83ffd7,2);rim.position.set(5,3,4);previewScene.add(rim);const platform=mesh(new THREE.CylinderGeometry(2.25,2.5,.28,48),mat(0x254d44,.72));platform.position.y=-.15;previewScene.add(platform);refreshPreview3D()}
function drawPreview(){refreshPreview3D()}
function refreshPreview3D(){if(!previewScene)return;if(previewCreature)previewScene.remove(previewCreature);previewCreature=makeCreature(colors[state.color],1.15);previewCreature.position.y=.05;previewScene.add(previewCreature)}
preview.addEventListener('pointerdown',e=>{previewDrag=true;previewLast={x:e.clientX,y:e.clientY};preview.classList.add('dragging');preview.setPointerCapture(e.pointerId)});preview.addEventListener('pointermove',e=>{if(!previewDrag)return;previewYaw+=(e.clientX-previewLast.x)*.009;previewPitch=THREE.MathUtils.clamp(previewPitch+(e.clientY-previewLast.y)*.006,-.35,.45);previewLast={x:e.clientX,y:e.clientY}});preview.addEventListener('pointerup',e=>{previewDrag=false;preview.classList.remove('dragging');preview.releasePointerCapture(e.pointerId)});preview.addEventListener('wheel',e=>{previewZoom=THREE.MathUtils.clamp(previewZoom+Math.sign(e.deltaY)*.4,4.7,8);e.preventDefault()},{passive:false});

// Three.js open-world scene
const canvas=$('#game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,500);
const clock=new THREE.Clock();
const worldRoot=new THREE.Group();scene.add(worldRoot);
let playerMesh,terrain,playerMixer,spawned=[],obstacles=[];
const keys={};
const motion={velocity:new THREE.Vector3(),yaw:Math.PI,pitch:.38,distance:10,dragging:false,lastX:0,lastY:0};

function seeded(seed){return()=>((seed=Math.imul(seed,1664525)+1013904223|0)>>>0)/4294967296}
function terrainHeight(x,z){return Math.sin(x*.045)*2.0+Math.cos(z*.052)*1.55+Math.sin((x+z)*.025)*1.2+Math.sin(Math.hypot(x,z)*.07)*.65}
function mat(color,rough=.78,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:0,emissive,emissiveIntensity:emissive ? .55 : 0})}
function mesh(geo,material,cast=true){const m=new THREE.Mesh(geo,material);m.castShadow=cast;m.receiveShadow=true;return m}
function add(group,obj,x=0,y=0,z=0){obj.position.set(x,y,z);group.add(obj);return obj}

function makeCreature(color=colors[state.color],scale=1,wild=false){
  const g=new THREE.Group(),dark=mat(0x173d35,.65),skin=mat(color,.72),white=mat(0xfffdf0,.35),pupil=mat(0x102a26,.3);
  const bodyGeo=state.body===1?new THREE.CapsuleGeometry(.72,1.25,10,18):state.body===2?new THREE.SphereGeometry(1.02,24,16):new THREE.SphereGeometry(1,24,18);
  const body=mesh(bodyGeo,skin);body.scale.set((state.body===1 ? 1 : 1.15)*state.width,(state.body===1 ? .82 : 1)*state.spine,state.body===1 ? 1.35 : 1.05);body.position.y=1.55;g.add(body);
  for(let pair=0;pair<state.legPairs;pair++)for(const side of[-1,1]){const limb=new THREE.Group(),row=state.legPairs===1 ? 0 : (pair/(state.legPairs-1)-.5)*1.15;limb.position.set(side*.48*state.width,.9,row);const upperLength=state.legs===2 ? .72 : .5,lowerLength=state.legs===0 ? .42 : .66,upper=mesh(new THREE.CapsuleGeometry(.16,upperLength,8,12),skin);upper.position.set(side*.1,-upperLength*.45,0);upper.rotation.z=side*(state.legs===2 ? .42 : .12);limb.add(upper);const knee=mesh(new THREE.SphereGeometry(.18,12,9),skin);knee.position.set(side*(state.legs===2 ? .3 : .1),-.48,0);limb.add(knee);const lower=mesh(new THREE.CapsuleGeometry(.13,lowerLength,8,12),skin);lower.position.set(side*(state.legs===1 ? .24 : .13),-.7,0);lower.rotation.z=side*(state.legs===1 ? -.35 : state.legs===2 ? -.22 : .04);limb.add(lower);const foot=mesh(new THREE.SphereGeometry(.25,16,10),dark);foot.scale.set(state.legs===0 ? 1.55 : 1.05,.38,state.legs===2 ? 1.9 : 1.45);foot.position.set(side*(state.legs===1 ? .36 : .16),-1.05,-.12);limb.add(foot);g.add(limb)}
  for(let pair=0;pair<state.arms;pair++)for(const side of[-1,1]){const arm=mesh(new THREE.CapsuleGeometry(.12,.72,8,12),skin);arm.position.set(side*(.9*state.width),1.5+pair*.28,-.05+pair*.28);arm.rotation.z=side*(.75-pair*.12);g.add(arm);const hand=mesh(new THREE.SphereGeometry(.19,14,10),dark);hand.position.set(side*(1.15*state.width),1.18+pair*.25,-.05+pair*.28);g.add(hand)}
  for(const side of[-1,1]){const eye=mesh(new THREE.SphereGeometry(.29,18,14),white);eye.position.set(state.faceX/105+side*.39,1.98-state.faceY/100,-.78);eye.userData.editPart='face';g.add(eye);const dot=mesh(new THREE.SphereGeometry(.12,14,10),pupil);dot.position.set(state.faceX/105+side*.41,1.98-state.faceY/100,-1.02);dot.userData.editPart='face';g.add(dot)}
  if(state.mouth===1){const beak=mesh(new THREE.ConeGeometry(.33,.8,8),mat(0xffcc55));beak.rotation.x=-Math.PI/2;beak.position.set(state.faceX/105,1.5-state.faceY/100,-1.03);beak.userData.editPart='face';g.add(beak)}else{const mouth=mesh(new THREE.TorusGeometry(.3,.055,8,18,Math.PI),dark);mouth.rotation.set(0,0,Math.PI);mouth.position.set(state.faceX/105,1.52-state.faceY/100,-.98);mouth.userData.editPart='face';g.add(mouth)}
  if(state.body===2)for(let i=-2;i<=2;i++){const spike=mesh(new THREE.ConeGeometry(.13,.42,5),dark);spike.position.set(i*.32,2.5-Math.abs(i)*.05,0);g.add(spike)}
  const belly=mesh(new THREE.SphereGeometry(.76,20,14),new THREE.MeshStandardMaterial({color,roughness:.8,transparent:true,opacity:.35}));belly.scale.set(1,.72,.95);belly.position.set(0,1.35,-.58);g.add(belly);g.scale.setScalar(scale);g.userData.body=body;g.userData.wild=wild;return g;
}
function makeTree(r,p){const g=new THREE.Group(),trunk=mesh(new THREE.CylinderGeometry(.22,.48,2.8,10),mat(p===1?0x4b2924:0x6a4d34));trunk.position.y=1.4;trunk.rotation.z=(r-.5)*.12;g.add(trunk);if(p===3){for(let i=0;i<4;i++){const arm=mesh(new THREE.CapsuleGeometry(.12,.9,6,10),mat(0x578d4b));arm.position.set((i-1.5)*.3,2.25+i*.24,0);arm.rotation.z=(i-1.5)*.38;g.add(arm)}}else{const leafColor=p===2?0x53d8b5:p===1?0xbd4939:0x5fae55;for(let i=0;i<7;i++){const crown=mesh(new THREE.SphereGeometry(.72+r*.25,16,12),mat(leafColor,.88,p===2?0x123f37:0));const a=i/7*Math.PI*2;crown.scale.set(1.1,.85+((i+1)%3)*.12,1);crown.position.set(Math.cos(a)*.72,2.9+Math.sin(i*2.1)*.35,Math.sin(a)*.52);g.add(crown)}}return g}
function makeRock(p,r){const geo=new THREE.SphereGeometry(.55+r*1.1,12,8),m=mesh(geo,mat(p===1?0x57403a:p===3?0x9b7548:0x70847b));m.scale.set(1.15,.45+r*.55,.9);m.rotation.y=r*5;return m}
function makeFlower(color,r){const g=new THREE.Group(),stem=mesh(new THREE.CylinderGeometry(.025,.035,.45,6),mat(0x4f994d),false);stem.position.y=.22;g.add(stem);for(let i=0;i<5;i++){const petal=mesh(new THREE.SphereGeometry(.1,10,7),mat(color,.65),false);const a=i/5*Math.PI*2;petal.scale.set(1.5,.5,1);petal.position.set(Math.cos(a)*.12,.48,Math.sin(a)*.12);g.add(petal)}return g}
function makeBone(){const g=new THREE.Group(),ivory=mat(0xfff0bd,.45,0x594712);const shaft=mesh(new THREE.CylinderGeometry(.14,.14,1.2,10),ivory);shaft.rotation.z=Math.PI/2;g.add(shaft);for(const x of[-.64,.64])for(const z of[-.13,.13]){const end=mesh(new THREE.SphereGeometry(.22,12,9),ivory);end.position.set(x,0,z);g.add(end)}const ring=mesh(new THREE.TorusGeometry(.9,.035,8,30),new THREE.MeshBasicMaterial({color:0xe7ff70,transparent:true,opacity:.7}),false);ring.rotation.x=Math.PI/2;ring.position.y=-.28;g.add(ring);g.scale.setScalar(1.25);return g}
function makeFood(kind){const g=new THREE.Group();if(kind==='plant'){const fruit=mesh(new THREE.SphereGeometry(.32,16,12),mat(0xe45b66,.55));fruit.scale.y=.82;g.add(fruit);const leaf=mesh(new THREE.SphereGeometry(.18,10,7),mat(0x4f9c50),false);leaf.scale.set(1.5,.25,.75);leaf.position.set(.12,.32,0);g.add(leaf)}else{const meat=mesh(new THREE.CapsuleGeometry(.22,.55,8,12),mat(0xd97868,.62));meat.rotation.z=Math.PI/2;g.add(meat);const bone=mesh(new THREE.CylinderGeometry(.07,.07,.95,7),mat(0xf2dfb7),false);bone.rotation.z=Math.PI/2;g.add(bone)}return g}
function makeNest(){const g=new THREE.Group();for(let i=0;i<18;i++){const stick=mesh(new THREE.CylinderGeometry(.06,.08,2.3,5),mat(0x745131));stick.rotation.set(Math.PI/2,(i%3)*.2,i/18*Math.PI*2);stick.position.set(Math.cos(i/18*6.28)*1.2,.1,Math.sin(i/18*6.28)*1.2);g.add(stick)}return g}

function clearWorld(){while(worldRoot.children.length)worldRoot.remove(worldRoot.children[0]);spawned=[];obstacles=[]}
function buildWorld(play=true){
  clearWorld();const p=planets[state.planet],rnd=seeded(800+state.planet*541+state.tier*31);scene.background=new THREE.Color(p.sky);scene.fog=new THREE.FogExp2(p.fog,.009);
  const hemi=new THREE.HemisphereLight(0xfff4d6,p.ground,2.25);worldRoot.add(hemi);const sun=new THREE.DirectionalLight(0xfff0c2,3.4);sun.position.set(-35,48,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-55;sun.shadow.camera.right=sun.shadow.camera.top=55;sun.shadow.camera.far=140;worldRoot.add(sun);
  const geo=new THREE.PlaneGeometry(180,180,100,100);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,terrainColors=[];const base=new THREE.Color(p.ground),light=base.clone().offsetHSL(.025,.03,.09),dark=base.clone().offsetHSL(-.015,.02,-.08);for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),h=terrainHeight(x,z);pos.setY(i,h);const noise=Math.sin(x*.19)*Math.cos(z*.17)*.5+.5,c=dark.clone().lerp(light,noise*.7+.15);terrainColors.push(c.r,c.g,c.b)}geo.setAttribute('color',new THREE.Float32BufferAttribute(terrainColors,3));geo.computeVertexNormals();terrain=mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.95}),false);worldRoot.add(terrain);
  const pond=mesh(new THREE.CircleGeometry(9,40),new THREE.MeshPhysicalMaterial({color:p.accent,transparent:true,opacity:.62,roughness:.15,metalness:.05}));pond.rotation.x=-Math.PI/2;pond.position.set(27,terrainHeight(27,-22)+.15,-22);worldRoot.add(pond);
  add(worldRoot,makeNest(),0,terrainHeight(0,0)+.1,0);
  for(let i=0;i<150;i++){const a=rnd()*6.28,d=7+Math.sqrt(rnd())*78,x=Math.cos(a)*d,z=Math.sin(a)*d;if(Math.hypot(x-27,z+22)<11)continue;const obj=rnd()>.34?makeTree(rnd(),state.planet):makeRock(state.planet,rnd());const s=.65+rnd()*1.35;obj.scale.setScalar(s);obj.rotation.y=rnd()*6.28;add(worldRoot,obj,x,terrainHeight(x,z),z);if(s>.95)obstacles.push({x,z,r:state.planet===3?1:1.5*s})}
  for(let i=0;i<420;i++){const a=rnd()*6.28,d=5+Math.sqrt(rnd())*82,x=Math.cos(a)*d,z=Math.sin(a)*d;if(rnd()>.84&&state.planet!==1){const flower=makeFlower([0xf9d56e,0xf58a9d,0xc9a5ff,0xffffff][i%4],rnd());flower.scale.setScalar(.7+rnd()*.8);add(worldRoot,flower,x,terrainHeight(x,z),z)}else{const grass=mesh(new THREE.ConeGeometry(.055+rnd()*.08,.35+rnd()*.65,7),mat(p.accent,.92,state.planet===2?p.accent:0),false);grass.scale.x=.45;grass.rotation.z=(rnd()-.5)*.3;grass.rotation.y=rnd()*6.28;add(worldRoot,grass,x,terrainHeight(x,z)+.2,z)}}
  if(play)spawnGameplay(rnd);else{const display=makeCreature(colors[state.color],2);add(worldRoot,display,0,terrainHeight(0,0),0);playerMesh=display}
}
const nameA=['Moss','Nib','Brum','Zig','Tuff','Glim','Snor','Plum','Vex','Wob'],nameB=['whisk','ble','snout','kin','aroo','hopper','munch','ling','beak','tail'];
function speciesName(i){return nameA[(i*7+state.planet*3)%10]+nameB[(i*3+state.planet)%10]}
function spawnGameplay(rnd){state.entities=[];state.player.x=0;state.player.z=0;playerMesh=makeCreature(colors[state.color],.85);add(worldRoot,playerMesh,0,terrainHeight(0,0),0);
  for(let i=0;i<18;i++){const a=rnd()*6.28,d=12+rnd()*64,x=Math.cos(a)*d,z=Math.sin(a)*d,obj=makeCreature(colors[(i+state.planet+2)%colors.length],.65+rnd()*.2,true);add(worldRoot,obj,x,terrainHeight(x,z),z);const e={type:'creature',x,z,name:speciesName(i),friendly:rnd()>.45,hp:3,done:false,mesh:obj,angle:rnd()*6.28,speed:.45+rnd()*.55,homeX:x,homeZ:z};state.entities.push(e);spawned.push(obj)}
  for(let i=0;i<22;i++){const a=rnd()*6.28,d=i===0?4:8+rnd()*69,x=i===0?4:Math.cos(a)*d,z=i===0?0:Math.sin(a)*d,obj=makeBone();add(worldRoot,obj,x,terrainHeight(x,z)+.55,z);const e={type:'bone',x,z,taken:false,mesh:obj,phase:rnd()*6.28};state.entities.push(e);spawned.push(obj)}
  for(let i=0;i<45;i++){const a=rnd()*6.28,d=5+rnd()*73,x=Math.cos(a)*d,z=Math.sin(a)*d,kind=rnd()>.7?'meat':'plant',obj=makeFood(kind);add(worldRoot,obj,x,terrainHeight(x,z)+.35,z);const e={type:'food',kind,x,z,taken:false,mesh:obj,phase:rnd()*6.28};state.entities.push(e);spawned.push(obj)}
}
function refreshPlayer(){if(!playerMesh)return;const wasPlaying=state.screen==='play',x=playerMesh.position.x,z=playerMesh.position.z;worldRoot.remove(playerMesh);playerMesh=makeCreature(colors[state.color],wasPlaying ? .85 : 2);add(worldRoot,playerMesh,x,terrainHeight(x,z),z)}
function startGame(){state.name=$('#creature-name').value.trim()||'Pip';state.hunger=100;$('#hud-name').textContent=state.name.toUpperCase();$('#hud-diet').textContent=traits.diet[state.diet][0].toUpperCase();$('#portrait').style.background=colors[state.color];buildWorld(true);showScreen('play');updateHunger();toast(`Welcome to ${planets[state.planet].name}, ${state.name}! Find food and evolution bones.`)}

addEventListener('keydown',e=>{keys[e.code]=true;if(state.screen==='play'&&!state.paused){if(e.code==='KeyE')interact('collect');if(e.code==='KeyF')interact('friend');if(e.code==='Space'){e.preventDefault();interact('attack')}if(e.code==='Escape')pause(true)}});addEventListener('keyup',e=>keys[e.code]=false);
canvas.addEventListener('pointerdown',e=>{if(state.screen!=='play')return;motion.dragging=true;motion.lastX=e.clientX;motion.lastY=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.classList.add('looking')});
canvas.addEventListener('pointermove',e=>{if(!motion.dragging)return;const dx=e.clientX-motion.lastX,dy=e.clientY-motion.lastY;motion.lastX=e.clientX;motion.lastY=e.clientY;motion.yaw-=dx*.006;motion.pitch=THREE.MathUtils.clamp(motion.pitch+dy*.004,.12,.78)});
canvas.addEventListener('pointerup',e=>{motion.dragging=false;canvas.releasePointerCapture(e.pointerId);canvas.classList.remove('looking')});
canvas.addEventListener('wheel',e=>{if(state.screen==='play'){motion.distance=THREE.MathUtils.clamp(motion.distance+Math.sign(e.deltaY),6.5,14);e.preventDefault()}},{passive:false});
function nearestUsable(types,radius=4.8){let found=null,best=radius;for(const e of state.entities){if(e.taken||e.done||!e.mesh.visible||!types.includes(e.type))continue;const d=Math.hypot(e.x-state.player.x,e.z-state.player.z);if(d<best){best=d;found=e}}return found}
function interact(action){let t=state.target;if(action==='collect')t=nearestUsable(['bone','food']);else t=nearestUsable(['creature']);if(!t){if(action==='collect')toast('Move closer to food or a glowing bone');return}if(t.type==='bone'&&action==='collect'){t.taken=true;t.mesh.visible=false;state.bones++;$('#bone-count').textContent=state.bones;toast('Evolution bone collected!');updateObjective()}else if(t.type==='food'&&action==='collect'){const canEat=state.diet===1||(state.diet===0&&t.kind==='plant')||(state.diet===2&&t.kind==='meat');if(!canEat){toast(`Your ${traits.diet[state.diet][0].toLowerCase()} cannot digest that`);return}t.taken=true;t.mesh.visible=false;state.hunger=Math.min(100,state.hunger+32);updateHunger();toast(t.kind==='plant'?'Juicy fruit restored hunger':'Fresh protein restored hunger')}else if(t.type==='creature'){if(action==='friend'){if(t.friendly||getStats().social>=7){t.done=true;t.friendly=true;t.mesh.userData.friend=true;toast(`${t.name} joined your pack!`);awardBone()}else toast(`${t.name} is wary — try a gentler creature`)}if(action==='attack'){t.hp--;t.mesh.scale.multiplyScalar(.93);toast(`You struck ${t.name}`);if(t.hp<=0){t.done=true;t.mesh.visible=false;toast(`${t.name} was defeated. DNA gained.`);awardBone()}else{state.health=Math.max(0,state.health-(state.adaptation===1?4:8));updateHealth();if(!state.health){state.health=100;state.hunger=65;state.player.x=state.player.z=0;toast('You tumbled back to the nest!');updateHealth();updateHunger()}}}}}
function awardBone(){state.bones++;$('#bone-count').textContent=state.bones;updateObjective()}
function updateObjective(){const n=Math.min(state.bones,state.boneGoal);$('#objective-progress').style.width=`${n/state.boneGoal*100}%`;$('#objective-text').textContent=n>=state.boneGoal?'Your DNA is ready — evolve!':n===0?'Find your first bone':`Gather ${state.boneGoal-n} more evolution bone${state.boneGoal-n===1?'':'s'}`;$('#evolve-btn').classList.toggle('hidden',n<state.boneGoal)}
function updateHealth(){$('#health-bar').style.width=state.health+'%';$('#health-text').textContent=state.health}
function updateHunger(){$('#hunger-bar').style.width=state.hunger+'%';$('#hunger-text').textContent=Math.ceil(state.hunger);$('#hunger-bar').style.background=state.hunger<25?'#ff7058':'#f1bd54'}
function pause(on){state.paused=on;$('#pause-modal').classList.toggle('hidden',!on)}
function toast(s){const el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function openEvolution(){state.paused=true;$('#evolve-modal').classList.remove('hidden');const opts=[['Fleet Feet','⚡','Move 25% faster'],['Thorn Hide','✦','Take half damage'],['Kindred Call','♫','Befriend wary creatures']];$('#evolution-options').innerHTML=opts.map((o,i)=>`<button class="evolution-option" data-i="${i}"><span>${o[1]}</span><strong>${o[0]}</strong><small>${o[2]}</small></button>`).join('');$$('.evolution-option').forEach(b=>b.onclick=()=>{state.tier++;state.adaptation=+b.dataset.i;state.bones=0;state.boneGoal+=2;$('#bone-count').textContent=0;$('#bone-goal').textContent=state.boneGoal;$('#evolve-modal').classList.add('hidden');state.paused=false;buildWorld(true);updateObjective();toast(`Evolution ${state.tier+1}: ${opts[+b.dataset.i][0]} awakened!`)})}

function collides(x,z){return obstacles.some(o=>Math.hypot(x-o.x,z-o.z)<o.r+.48)}
function update(dt,time){if(state.screen!=='play'||state.paused)return;const side=(keys.KeyD?1:0)-(keys.KeyA?1:0),forward=(keys.KeyW?1:0)-(keys.KeyS?1:0),hasInput=Math.hypot(side,forward)>0;const camForward=new THREE.Vector3(-Math.sin(motion.yaw),0,-Math.cos(motion.yaw)),camRight=new THREE.Vector3(-camForward.z,0,camForward.x),wish=new THREE.Vector3();wish.addScaledVector(camForward,forward).addScaledVector(camRight,side);if(hasInput)wish.normalize();const maxSpeed=(keys.ShiftLeft?9.2:5.4)*(state.adaptation===0?1.25:1)*(1+state.legs*.08),targetVelocity=wish.multiplyScalar(maxSpeed),response=1-Math.exp(-(hasInput?11:8)*dt);motion.velocity.lerp(targetVelocity,response);if(motion.velocity.length()<.035)motion.velocity.set(0,0,0);const nx=state.player.x+motion.velocity.x*dt,nz=state.player.z+motion.velocity.z*dt;if(Math.hypot(nx,state.player.z)<84&&!collides(nx,state.player.z))state.player.x=nx;else motion.velocity.x=0;if(Math.hypot(state.player.x,nz)<84&&!collides(state.player.x,nz))state.player.z=nz;else motion.velocity.z=0;if(motion.velocity.lengthSq()>.04){const targetAngle=Math.atan2(-motion.velocity.x,-motion.velocity.z),delta=Math.atan2(Math.sin(targetAngle-playerMesh.rotation.y),Math.cos(targetAngle-playerMesh.rotation.y));playerMesh.rotation.y+=delta*(1-Math.exp(-13*dt));const stride=Math.min(1,motion.velocity.length()/5.4);playerMesh.userData.body.position.y=1.55+Math.sin(time*(8+stride*4))*.07*stride;playerMesh.userData.body.rotation.z=Math.sin(time*6)*.025*stride}
  playerMesh.position.set(state.player.x,terrainHeight(state.player.x,state.player.z),state.player.z);state.hunger=Math.max(0,state.hunger-dt*(hasInput ? (keys.ShiftLeft ? .72 : .38) : .19));if(state.hunger===0){state.health=Math.max(0,state.health-dt*4);updateHealth()}updateHunger();
  let near=null,nearDist=4.6;
  for(const e of state.entities){if(e.taken||(!e.mesh.visible))continue;if(e.type==='creature'&&!e.done){e.angle+=dt*(Math.sin(e.homeX)*.12);e.x+=Math.sin(e.angle)*e.speed*dt;e.z+=Math.cos(e.angle)*e.speed*dt;if(Math.hypot(e.x-e.homeX,e.z-e.homeZ)>7)e.angle+=Math.PI;e.mesh.position.set(e.x,terrainHeight(e.x,e.z),e.z);e.mesh.rotation.y=e.angle;e.mesh.userData.body.position.y=1.55+Math.sin(time*4+e.homeX)*.05;if(e.mesh.userData.friend){const d=Math.hypot(e.x-state.player.x,e.z-state.player.z);if(d>5){e.x+=(state.player.x-e.x)/d*dt*2;e.z+=(state.player.z-e.z)/d*dt*2}}}else if(e.type==='bone'){e.mesh.rotation.y+=dt;e.mesh.position.y=terrainHeight(e.x,e.z)+.55+Math.sin(time*2+e.phase)*.15}else if(e.type==='food'){e.mesh.rotation.y+=dt*.55;e.mesh.position.y=terrainHeight(e.x,e.z)+.35+Math.sin(time*2+e.phase)*.06}const d=Math.hypot(e.x-state.player.x,e.z-state.player.z);if(!e.done&&d<nearDist){nearDist=d;near=e}}
  state.target=near;$('#target-card').classList.toggle('hidden',!near);if(near){const bone=near.type==='bone',food=near.type==='food';$('#target-kind').textContent=bone?'ANCIENT REMAINS':food?'EDIBLE FIND':near.friendly?'CURIOUS CREATURE':'WARY CREATURE';$('#target-name').textContent=bone?'EVOLUTION BONE':food?(near.kind==='plant'?'WILD FRUIT':'FRESH MEAT'):near.name.toUpperCase();$('#target-mood').textContent=bone||food?'Press E to pick up':near.friendly?'Open to friendship':'Watching you closely';$('.target-actions').style.display=bone||food?'none':'block'}
}
function renderPreview3D(time){if(!previewRenderer||state.screen!=='creator')return;const rect=preview.getBoundingClientRect(),w=Math.max(1,rect.width),h=Math.max(1,rect.height);if(previewRenderer.domElement.width!==Math.floor(w*previewRenderer.getPixelRatio())||previewRenderer.domElement.height!==Math.floor(h*previewRenderer.getPixelRatio())){previewRenderer.setSize(w,h,false);previewCamera.aspect=w/h;previewCamera.updateProjectionMatrix()}if(previewCreature){previewCreature.rotation.y=previewYaw+(previewDrag?0:Math.sin(time*.35)*.08);previewCreature.rotation.x=previewPitch}previewCamera.position.set(0,2.1,previewZoom);previewCamera.lookAt(0,1.35,0);previewRenderer.render(previewScene,previewCamera)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),time=clock.elapsedTime;update(dt,time);const playing=state.screen==='play'&&playerMesh;if(playing){const focus=new THREE.Vector3(state.player.x,terrainHeight(state.player.x,state.player.z)+1.45,state.player.z),horizontal=Math.cos(motion.pitch)*motion.distance;const desired=new THREE.Vector3(focus.x+Math.sin(motion.yaw)*horizontal,focus.y+Math.sin(motion.pitch)*motion.distance,focus.z+Math.cos(motion.yaw)*horizontal);desired.y=Math.max(desired.y,terrainHeight(desired.x,desired.z)+1.1);camera.position.lerp(desired,1-Math.exp(-7*dt));const lookAhead=motion.velocity.clone().multiplyScalar(.22);camera.lookAt(focus.add(lookAhead))}else{camera.position.set(Math.sin(time*.08)*18,10,Math.cos(time*.08)*18);camera.lookAt(0,1,0)}renderer.render(scene,camera);renderPreview3D(time)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});renderer.setSize(innerWidth,innerHeight,false);
initPreview3D();initUI();buildWorld(false);animate();
