/*
 * waveSystem — the shape of a run.
 *
 * The arena used to trickle in three wandering bots forever, so there was
 * nothing to survive and nothing to reach. A run is now a ladder of waves:
 * each one sends a fixed number of tougher snowmen, and clearing it buys you a
 * short breather to spend score in the workshop before the next one starts.
 *
 * ── Tweaking the difficulty ────────────────────────────────────────────────
 * WAVE_TABLE is the whole design. Add or edit rows to reshape the early game;
 * anything past the last row is generated by `proceduralWave()` so a run never
 * runs out of waves. Fields:
 *
 *   enemies     how many spawn in total this wave
 *   maxAlive    how many may be on the field at once
 *   health      hit points per snowman
 *   speed       units per second they close on you
 *   fireRate    milliseconds between their shots (lower = scarier)
 *   spawnGap    milliseconds between arrivals
 */

export const INTERMISSION_MS = 9000;

export const WAVE_TABLE = [
    { enemies: 4,  maxAlive: 3, health: 50,  speed: 3.0, fireRate: 3000, spawnGap: 1100 },
    { enemies: 6,  maxAlive: 4, health: 60,  speed: 3.4, fireRate: 2700, spawnGap: 1000 },
    { enemies: 8,  maxAlive: 5, health: 70,  speed: 3.8, fireRate: 2400, spawnGap: 900 },
    { enemies: 10, maxAlive: 6, health: 85,  speed: 4.2, fireRate: 2150, spawnGap: 820 },
    { enemies: 12, maxAlive: 7, health: 100, speed: 4.6, fireRate: 1950, spawnGap: 740 },
    { enemies: 14, maxAlive: 8, health: 120, speed: 5.0, fireRate: 1800, spawnGap: 660 }
];

// Past the hand-authored table the curve keeps climbing, but gently enough that
// a good run ends because the player slipped, not because the numbers spiked.
function proceduralWave(waveNumber) {
    const step = waveNumber - WAVE_TABLE.length;
    return {
        enemies: Math.min(30, 14 + step * 2),
        maxAlive: Math.min(12, 8 + Math.floor(step / 2)),
        health: Math.min(320, 120 + step * 18),
        speed: Math.min(7.5, 5.0 + step * 0.22),
        fireRate: Math.max(900, 1800 - step * 90),
        spawnGap: Math.max(360, 660 - step * 30)
    };
}

export function getWave(waveNumber) {
    return waveNumber <= WAVE_TABLE.length
        ? WAVE_TABLE[waveNumber - 1]
        : proceduralWave(waveNumber);
}

// Killing something in a later wave is worth more, so banking score for a
// bigger upgrade stays a real choice rather than always the wrong one.
export function killReward(waveNumber) {
    return 60 + waveNumber * 15;
}

export function clearBonus(waveNumber) {
    return 150 + waveNumber * 50;
}

/*
 * Tracks progress through one wave. The caller drives it with update() and acts
 * on what it returns; it deliberately owns no Three.js state so it stays easy
 * to read and to test.
 */
export function createWaveRunner() {
    let waveNumber = 0;
    let config = null;
    let spawned = 0;
    let killed = 0;
    let lastSpawnAt = 0;
    let phase = 'idle'; // idle | intermission | fighting
    let phaseEndsAt = 0;

    function beginIntermission(now, durationMs = INTERMISSION_MS) {
        phase = 'intermission';
        phaseEndsAt = now + durationMs;
    }

    function beginWave(now) {
        waveNumber += 1;
        config = getWave(waveNumber);
        spawned = 0;
        killed = 0;
        lastSpawnAt = now - config.spawnGap; // first snowman arrives immediately
        phase = 'fighting';
    }

    function reset(now) {
        waveNumber = 0;
        config = null;
        spawned = 0;
        killed = 0;
        phase = 'intermission';
        // A short pause before wave 1 so the player can get their bearings.
        phaseEndsAt = now + 3500;
    }

    function recordKill() {
        killed += 1;
    }

    /*
     * Returns the events the caller should act on this frame:
     *   { waveStarted, spawn, waveCleared, secondsToNextWave }
     */
    function update(now, aliveCount) {
        const events = { waveStarted: false, spawn: false, waveCleared: false, secondsToNextWave: 0 };

        if (phase === 'intermission') {
            if (now >= phaseEndsAt) {
                beginWave(now);
                events.waveStarted = true;
            } else {
                events.secondsToNextWave = Math.ceil((phaseEndsAt - now) / 1000);
            }
            return events;
        }

        if (phase !== 'fighting') return events;

        const moreToSend = spawned < config.enemies;
        if (moreToSend && aliveCount < config.maxAlive && now - lastSpawnAt >= config.spawnGap) {
            spawned += 1;
            lastSpawnAt = now;
            events.spawn = true;
        }

        // The wave ends when everything sent has been dealt with.
        if (!moreToSend && aliveCount === 0) {
            events.waveCleared = true;
            beginIntermission(now);
        }

        return events;
    }

    return {
        update,
        reset,
        recordKill,
        beginIntermission,
        get waveNumber() { return waveNumber; },
        get config() { return config; },
        get phase() { return phase; },
        get remaining() { return config ? config.enemies - killed : 0; },
        get totalThisWave() { return config ? config.enemies : 0; }
    };
}
